// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk17GIxcilkNz0wp8rT7y1a9NvAQ4SatI',
    appId: '1:660967324609:web:7fa7119533485cbe3ccd40',
    messagingSenderId: '660967324609',
    projectId: 'chat-app-d1e28',
    authDomain: 'chat-app-d1e28.firebaseapp.com',
    storageBucket: 'chat-app-d1e28.appspot.com',
    measurementId: 'G-FKZG62N2SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJr9qMjADM1AuVXWOSqLtWpA-6ah3fNu8',
    appId: '1:660967324609:android:970fac7a218bab653ccd40',
    messagingSenderId: '660967324609',
    projectId: 'chat-app-d1e28',
    storageBucket: 'chat-app-d1e28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvybAIsNeUrcW292Xp_mxzN2jZsOCy_go',
    appId: '1:660967324609:ios:dc07a0eabe05b2d33ccd40',
    messagingSenderId: '660967324609',
    projectId: 'chat-app-d1e28',
    storageBucket: 'chat-app-d1e28.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

}